Destroy enemy
Lare1426/flippy-bit pull request #7
Opened 2022-11-03 10:22 UTC by Lare1426

This feature branch merges missiles into when the current displayed hexadecimal matches any of the enemies on the screen. Once that has happened it will save only 1 missile and shoot it up until it hits it's target (enemy).

2022-11-05 00:05 UTC, studleton requested changes
Overall quite polished, which mases sense considering the number of iterations and refinement. A good final product of that, which means it was worth it, not even considering what you've learned along the way.

A few minor comments.

2022-11-05 00:05 UTC, studleton commented on functions.py
> +from classes import Point, Triangle, Enemy
`ceil` and `Triangle` are unused.

2022-11-05 13:36 UTC, Lare1426 commented on classes.py
> +    binary = reduce(lambda string, box: string + str(int(box.current_bit)), binary_boxes, "")
Yes

2022-11-05 14:33 UTC, Lare1426 commented on classes.py
> +      self.missiles = [self.missiles[0]]
Because then it doesn't have anything to pull from the missiles

2022-11-08 18:16 UTC, studleton approved these changes

2022-11-08 18:18 UTC, merged